### ISSUE TITLE
Unable to load any Minilogue files.

### ISSUE THREAD

**Issue by zmixnyc** [gazzar/loguetools#10]
I am able to run the program in OSX 10.15.7 but when I attempt to load any files, nothing happens.

I have tried:

.mnlgpreset

.mnlgprog

.mniglib

Each time the main windows remain empty.

Any thoughts?

**Comment by gazzar** [comment]
Hi, I'm sorry I didn't look into this when you first mentioned it, but thank you for highlighting this. It only took me a couple of years to find the time (a couple of solid days) to look into this as part of the latest change I've made 😬. You were correct that a bug was introduced into the last couple of versions that broke minilogue file reading on the mac. In my testing, this version fixes that problem and also now runs on my mac, which runs Big Sur. Hopefully it also runs on more recent macOS versions.
