### ISSUE TITLE
Properly initialize VPM menu parameters 

### ISSUE THREAD

**Issue by Christedge** [gazzar/loguetools#7]
As a user of files converted from og to xd, I want to use the VPM engine with reasonably initialized default values, so that I do not need to reset all menu parameters before I can use the VPM engine.

Acceptance criteria:

- In patches converted from og to xd, all VPM menu parameters are initialized to "0%" instead of "99%".

**Comment by gazzar** [comment]
Check the defaults in the Init patch and consider setting it the same as that.

**Comment by Christedge** [comment]
Well, in the Init patches, all VPM menu parameters are initialized to »0%« instead of »99%«, just as requested above :) .

**Comment by gazzar** [comment]
Aha, yep, that was an error; fixed in source now. Thanks for the report on this one.
