### ISSUE TITLE
Set Y+ destination to LFO Intensity instead of cutoff

### ISSUE THREAD

**Issue by Christedge** [gazzar/loguetools#8]
Cutoff is not bad as a default, though since I tend to use Y+ as a vibrato most of the time, it would be helpful in case it could point to LFO intensity instead.

**Comment by gazzar** [comment]
I've changed this as requested in source. The Korg documentation on this appears to be completely wrong. I've made significant changes to the translation mappings now. When I release these changes, I'll be interested to hear whether this is improved.
