### ISSUE TITLE
Compensation for the lack of sustain of the xd's EG

### ISSUE THREAD

**Issue by Christedge** [gazzar/loguetools#9]
Many converted patches sound differently simply du to tha lack of sustain of the xd. Possible mitigations:

- Option 1: Add filter envelope sustain to the xd's filter cutoff, at least in case the attack is near zero.
- Option 2: Deduct the sustain level from envelope amount, at least in case
- …

**Comment by gazzar** [comment]
@Christedge I don't understand exactly you mean here. I think I would need some examples with numbers, or a clearer explanation. Even so, I don't think I will change this unless it can be universally applied, and I doubt that is possible.

**Comment by Christedge** [comment]
After editing a couple of patches this very day, I doubt the converter can actually do such automated adjustments. So feel free to close/delete this ticket.

**Comment by dobo365** [comment]
FYI, I have also implemented the conversion Minilogue XD / Prologue in my Prologue editor and librarian and I'm simply doing a straightforward conversion of the values to the same parameters.
I think that one should see such converter as a way to benefit from a patch coming from the other synth but just as a starting point for a new patch.
